name: Fly Deploy
on:
  push:
    paths:
      - Todo/demo3/settings.gradle
      - Todo/demo3/build.gradle
      - Todo/demo3/src/**
      - Todo/demo3/fly.toml
      - Todo/demo3/Dockerfile
      - .github/workflows/deploy.yml
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: application-secret.yml 생성
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
        run: |
          mkdir -p demo3/src/main/resources
          echo "$APPLICATION_SECRET" > demo3/src/main/resources/application-secret.yml
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        working-directory: ./demo3
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
